name: PyTest

on:
  push:
  pull_request:

#env:
#  COLUMNS: 120

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          python -m pip install pytest 
          python -m pip install coverage 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
      - name: Test with pytest  
        run: |  
          coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
  