name: PyTest

on:
  push:
  pull_request:

# env:
#  COLUMNS: 120

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

# also include optional dependencies for shinerainsevenlib

      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          python -m pip install pytest 
          python -m pip install pytest-mock 
          python -m pip install coverage
          python -m pip install crc
          python -m pip install xxhash
          python -m pip install apsw
          python -m pip install dateparser
          python -m pip install parse
          python -m pip install pyperclip
          python -m pip install pillow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
      - name: Test with pytest  
        run: |  
          coverage run -m pytest --capture=no -v tests/test_core/test_m0_text_io.py 
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
  